### ISSUE TITLE
📖 Revamp README and docs

### ISSUE THREAD

**Issue by edouard-lopez** [pure-fish/pure#339]
## Todo

* [ ] Improve banner colors
* [x] migrate doc to [mkdocs](https://www.mkdocs.org/)
	* [x] remove migration quote
	* [x] simplify install instruction
		* [x] only keep `fisher` instructions
		* [x] extract or collapse manual instructions
	* [x] Restrict `🖌️ Configuration` section to explaining how to configure feature/color/symbol
	* [x] Revamp `Features`, `Prompt Symbol` and `🔌 Features' Flags` to have a **feature focus doc**
	* [x] Improve `👍 Contribute` section
	* [x] Merge `👨‍💻 Maintainer` and `👏 Thanks` sections
	* [x] Reduce `Licence` section to title only
	* [x] Extract `Colours` to another page
* [x] Publish doc to gh-pages
* [ ] ~Generate screenshots for each features using https://github.com/OmarTawfik/terminal-screenshot~ will do in another PR, see #343 

##  Automatically generate screenshots

Using https://github.com/OmarTawfik/terminal-screenshot
```
❯ fish_prompt | npx terminal-screenshot --output out.png --background-color white --margin 5
```

### Preview
![out](https://github.com/pure-fish/pure/assets/1212392/9f6e36c3-d1dc-4ab7-a29e-c08ab411f978)
